enum DigitalAssetId {
  Dogecoin = 'dogecoin',
  ShibaInu = 'shiba-inu',
  Wif = 'wif',
  Pepe = 'pepe',
  Bome = 'bome',
  Neiro = 'neiro',
  Turbo = 'turbo',
  Bonk = 'bonk',
  Dogs = 'dogs',
  Meme = 'meme',
  Floki = 'floki',
  Notcoin = 'notcoin',
  Hmstr = 'hmstr',
  Popcat = 'popcat',
  Mew = 'mew',
  Cati = 'cati',
  Banana = 'banana',
  SunDog = 'sun-dog',
  Brett = 'brett',
  BabyDoge = 'baby-doge',
  Solana = 'solana',
  Toncoin = 'toncoin',
  Ethereum = 'ethereum',
}

export default DigitalAssetId;
